spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

logging:
  level:
    org.springframework:
      jdbc: DEBUG

security:
  jwt:
    secret-key: abcdefghijklmnopqrstuvwxyz0123456789
    expiration-time: 3600000 # 1 hour

payment:
  base-url: https://api.tosspayments.com
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
